baseURL: "https://gnehcuyz.github.io/PersonalBlog/"
languageCode: en-us
params:
  profileMode:
    enabled: true
    title: "Chengyu Zhang" # optional default will be site title
    subtitle: "Machine Learning Engineer || Software Engineer" 
    imageUrl: "images/profile.jpg" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size

  socialIcons:
    - name: github
      url: "https://github.com/gnehcuyz"
    - name: linkedin
      url: "https://www.linkedin.com/in/chengyuz"
    - name: email
      url: "mailto:chengyuz0921@gmail.com"
  
  # Post Settings:
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  # TocOpen: true
  author: Chengyu Zhang
  

# params:
#   defaultTheme: auto

#   # profileMode:
#   enabled: true
#   title: "Chengyu Zhang" 
#   subtitle: "Software Engineer || Machine Learning Engineer"
#   imageUrl: "static/images/profile.jpg" 
#   imageWidth: 180 # custom size
#   imageHeight: 180 # custom size
  


  # socialIcons:
  #   - name: github
  #     url: "https://github.com/gnehcuyz"
  #   - name: linkedin
  #     url: "https://www.linkedin.com/in/chengyuz"
  #   - name: email
  #     url: "mailto:chengyuz0921@gmail.com"

# Navbar Settings:
menu:
  main:
    - name: "Blog"
      url: "/posts/"
      weight: 3
    - name: "Research"
      url: "/research/"
      weight: 1
    - name: "Projects"
      url: "/projects/"
      weight: 2
    - name: "Reading"
      url: "/reading/"
      weight: 3
    - name: "About"
      url: "/about/"
      weight: 4


title: Chengyu Zhang
theme: PaperMod
math: true

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
    renderer:
      unsafe: true
