baseURL: "https://gnehcuyz.github.io/"
languageCode: en-us
params:
  defaultTheme: auto
  disableThemeToggle: false
  profileMode:
    enabled: true
    title: "Chengyu Zhang" # optional default will be site title
    subtitle: "Machine Learning Engineer || Software Engineer || Researcher" 
    imageUrl: "images/1.jpg" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size

  socialIcons:
    - name: github
      url: "https://github.com/gnehcuyz"
    - name: linkedin
      url: "https://www.linkedin.com/in/chengyuz"
    - name: email
      url: "mailto:chengyuz0921@gmail.com"
    - name: google-scholar
      url: "https://scholar.google.com/citations?user=4fT55M0AAAAJ&hl=en&oi=sra"

  
  # Post Settings:
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  # TocOpen: true
  author: Chengyu Zhang


# Navbar Settings:
menu:
  main:
    - name: "Experience"
      url: "/experience"
      weight: 4
    - name: "Research"
      url: "/research/"
      weight: 1
    - name: "Projects"
      url: "/projects/"
      weight: 4
    - name: "Blog"
      url: "/posts/"
      weight: 5
    - name: "Publications"
      url: "/publications/"
      weight: 2
    # - name: "Reading"
    #   url: "/reading/"
    #   weight: 3
    - name: "About me"
      url: "/about/"
      weight: 1
    - name: "Tags"
      url: "/tags/"
      weight: 5


title: Chengyu Zhang
theme: PaperMod
math: true

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
    renderer:
      unsafe: true

disablePathToLower: true
pluralizeListTitles: false