name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      # Setup Hugo
      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.140.2/hugo_extended_0.140.2_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      # Build the Hugo site
      - name: Build site
        run: ${RUNNER_TEMP}/hugo

      # Checkout the gh-pages branch
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: built-site

      # Deploy to gh-pages
      - name: Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -rf ${GITHUB_WORKSPACE}/built-site/*
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          touch ${GITHUB_WORKSPACE}/built-site/.nojekyll
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'gnehcuyz'
          git config user.email 'chengyuz0921@gmail.com'
          git commit -m 'Updated site' || echo "No changes to commit"
          git push origin gh-pages
